#!/bin/bash
# shellcheck disable=SC2164
DESTDIR=$(realpath initramfs)
KVER="6.7.6-arch1-2"
MODDIR=$(realpath orig_initramfs)

function create_symlinks() {
    pushd "${DESTDIR}"

    ln -s usr/lib lib
    ln -s usr/lib lib64

    pushd usr
    ln -s lib lib64
    ln -s bin sbin
    popd

    pushd var
    ln -s ../run run
    popd

    popd

}
function setup_files() {
    rm -rf "$DESTDIR"
    install -d "${DESTDIR}"/{dev,etc/{modprobe.d,},new_root,proc,run,sys,tmp,usr/{lib/modules/"$KVER"/kernel/drivers/{block,fs,net/ethernet,input},bin,local/{bin,lib,sbin}},var}
    cp -rf upstream/* "${DESTDIR}"
    chmod a+x -R "${DESTDIR}"/hooks
    cp config "${DESTDIR}"

    # busybox install
    pushd "${DESTDIR}"
    busybox --install -s usr/bin
    unlink "${DESTDIR}"/usr/bin/busybox
    cp -rf /usr/bin/busybox "${DESTDIR}"/usr/bin

    create_symlinks

    # copy modules
    cp -rf "$MODDIR"/usr/lib/modules/"$KVER"/kernel/drivers/net/ethernet/* "${DESTDIR}"/usr/lib/modules/"$KVER"/kernel/drivers/net/ethernet
    cp -rf "$MODDIR"/lib/modules/"${KVER}"/kernel/drivers/block/loop.* "${DESTDIR}"/usr/lib/modules/"$KVER"/kernel/drivers/block
    cp -rf "$MODDIR"/lib/modules/"${KVER}"/kernel/fs/squashfs "${DESTDIR}"/usr/lib/modules/"$KVER"/kernel/fs
    cp -rf "$MODDIR"/lib/modules/"${KVER}"/kernel/fs/overlayfs "${DESTDIR}"/usr/lib/modules/"$KVER"/kernel/fs
    cp -rf "$MODDIR"/lib/modules/"${KVER}"/kernel/drivers/input "${DESTDIR}"/usr/lib/modules/"$KVER"/kernel/drivers/input
    popd
}

function build_ipconfig() {
    local destdir
    destdir="${DESTDIR}"
    if [ ! -d mkinitcpio-nfs-utils ]; then
        git clone https://gitlab.archlinux.org/archlinux/mkinitcpio/mkinitcpio-nfs-utils.git
    else
        pushd mkinitcpio-nfs-utils
        git pull
        popd
    fi
    pushd mkinitcpio-nfs-utils/ipconfig
    make
    install -Dm755 ipconfig "$destdir"/usr/bin/ipconfig
    cp -rf /usr/lib/libc.so.6 "$destdir"/usr/lib
    cp -rf /usr/lib64/ld-linux-x86-64.so.2 "$destdir"/usr/lib64
}

function copy_utils() {
    # losetup
    cp -rf /usr/bin/losetup "${DESTDIR}"/usr/bin
    cp -rf /usr/lib/libsmartcols.so* "${DESTDIR}"/usr/lib
}

function build() {
    pushd "$DESTDIR"
    find . 2>/dev/null | cpio -o -R root:root -H newc | xz -1 --format=lzma >../initramfs-linux.img
    popd
}

function main() {
    setup_files
    build_ipconfig
    copy_utils
    build
}

main
